### ISSUE TITLE
permutation and analytical p-values should NOT be mixed on the same plot

### ISSUE THREAD

**Issue by bhaibeka** [bhklab/PharmacoDB-JS#380]
highly confusing. and showcase high discrepancies

I would add a toggle if permutation p-values are available and only show one type on the plots

https://test.pharmacodb.ca/biomarker?compound=lapatinib&gene=erbb2

**Comment by p-smirnov** [comment]
I agree with the idea of a toggle. However right now the mixing should not be happening in the first place. 

The CNV data looks broken here still, multiple copies of a dataset (both permutation) are appearing.
