### ISSUE TITLE
Gene page: "851 compounds have been tested on ERBB2, using data from " 

### ISSUE THREAD

**Issue by bhaibeka** [bhklab/PharmacoDB-JS#382]
I do not even know what that means, testing a drug on a gene?

https://test.pharmacodb.ca/genes/8228

crizotinib is at the top and ERBB2 is not even a target nor a biomarker for that drug?

**Comment by p-smirnov** [comment]
Related (closed) #218

My bad, I missed mentioning the case when we do have targets (I think the db may not have had target information at the time?).
