### ISSUE TITLE
Cell line Individual  Page

### ISSUE THREAD

**Issue by parinaznasr** [bhklab/PharmacoDB-JS#383]
- [x] PharmacoGx -rephrase to "Standardized name in PharmacoSet"
- [x] Message on N/A data sections
- [x] Molecular Profiling table - only keep used types
- [x] Molecular Profiling table - rename data types
- [x] "Drugs "Summary - rename the section + change the table (?)drugs tested such as mcf-7)
- [x] Add zoom in/out to AAC (Compounds) plot
- [x] AAC (Compounds) - add slider

**Comment by sisiranair** [comment]
@NiktaFeizi check NCI60 MCF7/ATCC. Concatenate to MCF-7 after review

**Comment by sisiranair** [comment]
- [ ] Drug Summary - page not loading
- [ ] AAC (Compounds) - add slider 
- [ ] Molecular Profiling table - rename data types
![Screen Shot 2021-09-16 at 12 59 24 PM](https://user-images.githubusercontent.com/41380598/133705191-74e71cf7-a37b-4b49-bf97-557531d2f83b.png)
