### ISSUE TITLE
Compound Summary page- make the bars clickable

### ISSUE THREAD

**Issue by parinaznasr** [bhklab/PharmacoDB-JS#387]
- [ ] Filter the table by clicking on the bars to show only compounds within the selected dataset bar. Add a "Show all" button to reset

**Comment by sisiranair** [comment]
@NiktaFeizi - [ ] Check cases like Pilocarpine where concatenated pubchem CIDs exist and they lead to invalid page. In such cases, select the index entry for the drug

**Comment by sisiranair** [comment]
- [ ] When clicked on Name or  SMILES or InChiKeys in "List of Compounds" table to sort, page goes blank.
