### ISSUE TITLE
Phenylbutazone data discrepancies

### ISSUE THREAD

**Issue by sisiranair** [bhklab/PharmacoDB-JS#433]
Link - https://pharmacodb.ca/compounds/PDBC03088

- [x] External links - mismatch with the other drug pages; the external database name should be in blue and linked
- [x] ChEMBL id should not shown in Drug Target Commons (also see erlotinib page)

**Comment by sisiranair** [comment]
- [ ] In Synonyms and IDs, no dataset name is shown. This compound is present in PRISM
- [ ] External links - mismatch with the other drug pages; the external database name should be in blue and linked
- [ ] ChEMB L id should not shown in Drug Target Commons

**Comment by mnakano** [comment]
Hi Sisira, I will take care of this.

**Comment by mnakano** [comment]
As per the discussion, the first issue appears to be a database issue. The fix for other items have been implemented and will be included in the next deployment.

**Comment by mnakano** [comment]
The first item of this issue has been transferred to [PharmacoDI Issue 7](https://github.com/bhklab/PharmacoDI/issues/7).

**Comment by ChristopherEeles** [comment]
The compound synonym issue is fixed in PharmacoDI. The changes will be reflected in the next database update.
