### ISSUE TITLE
Cellosaurus links are broken

### ISSUE THREAD

**Issue by p-smirnov** [bhklab/PharmacoDB-JS#482]
I think cellosaurus changed the link format. 

It used to be:
http://web.expasy.org/cellosaurus/CVCL_0618

Now it is:
https://www.cellosaurus.org/CVCL_0618 

We need to update our base url for the link out.

**Comment by gangeshberi** [comment]
Seems like the old links are redirected to the new ones, but I will update our code base to use the new link.
