### ISSUE TITLE
Web page is not loading

### ISSUE THREAD

**Issue by sgosline** [bhklab/PharmacoDB-JS#487]
Hi there, 

I tried to search the web page but am getting errors with the following pages:
https://pharmacodb.ca/genes
![image](https://user-images.githubusercontent.com/1847866/207209608-a5ec06a0-05b4-42b2-862f-6cf833ce3093.png)

https://pharmacodb.ca/compounds/PDBC00058
![image](https://user-images.githubusercontent.com/1847866/207209651-9c6db1b8-3faf-4930-83a6-a44bbb5c263e.png)

https://pharmacodb.ca/compounds/
![image](https://user-images.githubusercontent.com/1847866/207209690-e729d237-775d-4d66-b7a1-7f45edf60c7b.png)

Is this a problem with my firewall? Or is the site temporarily down?

-sara

**Comment by ChristopherEeles** [comment]
Hi @sgosline,

I am also unable to access the website at this time. We are currently investigating and should have the issue resolved by tomorrow.

Sorry for any inconvenience.

Best,
Christopher Eeles
Software Developer
Haibe-Kains Lab

**Comment by ChristopherEeles** [comment]
Hi @sgosline,

The temporary outage was likely related to updates to the Azure Web Service platform that we use for hosting. Everything appears to be working correctly now. 

Feel free to open a new issue if you encounter problems in the future.

Best,
Christopher Eeles
Software Developer
Haibe-Kains Lab

**Comment by sgosline** [comment]
Great, thanks so much!
